# Generated by Django 5.1.6 on 2025-02-23 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='contato',
            field=models.CharField(max_length=100, verbose_name='Contato do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade do Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Enviado', 'Enviado'), ('Recebido', 'Recebido'), ('Cancelado', 'Cancelado')], max_length=20, verbose_name='Status do Pedido'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(max_length=50, verbose_name='Categoria do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(error_messages={'blank': 'O código não pode estar em branco.', 'unique': 'Já existe um produto com este código.'}, max_length=50, unique=True, verbose_name='Código do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(verbose_name='Descrição do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, error_messages={'invalid': 'O preço deve ser um número decimal válido.'}, max_digits=10, verbose_name='Preço do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_minima',
            field=models.IntegerField(default=0, verbose_name='Quantidade Mínima'),
        ),
    ]
